global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'storagebox-server-monitoring'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: /metrics

  - job_name: 'app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /metrics
