FROM python:3.13.7-slim-bookworm
WORKDIR /app

RUN apt-get update && apt-get install -y curl entr && rm -rf /var/lib/apt/lists/*
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN groupadd --system appuser && useradd --system -g appuser appuser

COPY src /app/src
COPY tests /app/tests
COPY pytest.ini /app/pytest.ini
RUN chown -R appuser:appuser /app

USER appuser
EXPOSE 8000

# The container will stay alive indefinitely.
# `docker compose watch` will take over to execute tests.
ENTRYPOINT ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
